super-linter:
  image: ghcr.io/super-linter/super-linter:latest
  variables:
    - RUN_LOCAL: true
    - LOG_LEVEL: DEBUG
  volumes:
    - /builds/SiliconTao-Systems/STFjordi:/tmp/lint
  script:
    - env
    - echo "npx github/super-linter"
  only:
    - merge_requests
