before_script:
  - echo "Set the GITHUB_SHA value to the commit SHA"
  - export GITHUB_SHA=$(git rev-parse HEAD)

super-linter:
  image: github/super-linter
  before_script:
  - export GITHUB_SHA=$(git rev-parse --short=8 HEAD)
  script:
    - env
    - echo "npx github/super-linter"
  only:
    - merge_requests
