super-linter:
  image: ghcr.io/super-linter/super-linter:latest
  volumes:
    - /builds/SiliconTao-Systems/STFjordi:/tmp/lint
  script:
    - echo "npx github/super-linter"
  only:
    - merge_requests
