super-linter:
  image: ghcr.io/super-linter/super-linter:latest
  volumes:
    name: linter-temp
    path: /builds/SiliconTao-Systems/STFjordi:/tmp/lint
    mode: rw
    persist: true
  script:
    - env
    - echo "npx github/super-linter"
  only:
    - merge_requests
